"""add tag and shipment tag tables

Revision ID: 66a56f6e5170
Revises: 914dbd2d7aef
Create Date: 2026-03-30 18:51:14.418462

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from uuid import uuid4

# revision identifiers, used by Alembic.
revision: str = '66a56f6e5170'
down_revision: Union[str, Sequence[str], None] = '914dbd2d7aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('EXPRESS', 'STANDARD', 'FRAGILE', 'HEAVY', 'INTERNATIONAL', 'DOMESTIC', 'TEMPERATURE_CONTROLLED', 'GIFT', 'RETURN', 'DOCUMENTS', name='tagname'), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_tag',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('shipment_id', 'tag_id')
    )
    
    tag_table = sa.table('tag',
        sa.column('id', sa.UUID()),
        # Pass the name of the type as a keyword argument
        sa.column('name', sa.Enum(name='tagname')), 
        sa.column('instruction', sa.String())
    )
    
    op.bulk_insert(tag_table, [
        {'id': str(uuid4()), 'name': 'EXPRESS', 'instruction': 'Handle with priority speed.'},
        {'id': str(uuid4()), 'name': 'FRAGILE', 'instruction': 'Handle with extreme care, do not drop.'},
        {'id': str(uuid4()), 'name': 'HEAVY', 'instruction': 'Requires mechanical lift or two people.'},
        {'id': str(uuid4()), 'name': 'INTERNATIONAL', 'instruction': 'Requires customs clearance.'},
        {'id': str(uuid4()), 'name': 'DOMESTIC', 'instruction': 'Standard domestic shipping.'},
        {'id': str(uuid4()), 'name': 'TEMPERATURE_CONTROLLED', 'instruction': 'Maintain specific temperature range.'},
        {'id': str(uuid4()), 'name': 'GIFT', 'instruction': 'Wrap as a gift, handle with care.'},
        {'id': str(uuid4()), 'name': 'RETURN', 'instruction': 'For return shipments only.'},
        {'id': str(uuid4()), 'name': 'DOCUMENTS', 'instruction': 'Handle as important documents.'},
        {'id': str(uuid4()), 'name': 'STANDARD', 'instruction': 'Standard shipping, handle with care.'},
       
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
